<?php
/**
 * inc.delay.php — self-hosted "delay third-party JS until first interaction".
 *
 * Replaces WP Rocket's "Delay JS" for the only two third-party scripts the site
 * loads: Google Tag Manager and the HubSpot tracking loader. Vanilla JS, ~1 KB,
 * no plugin. Fires them on the FIRST user interaction (scroll / mousemove /
 * touch / key / pointer / click) OR after a timeout fallback, so zero-interaction
 * sessions still register a GA4 pageview and set the HubSpot `hubspotutk` cookie.
 * The gate is idempotent (fires once) and self-removes its listeners.
 *
 * Why delaying loses nothing: GTM events pushed to window.dataLayer before gtm.js
 * evaluates are queued (dataLayer is a plain array) and replayed on load. The GTM
 * <noscript> iframe stays in header.php for the JS-off case.
 *
 * Because GTM + HubSpot are injected here via createElement (not present in the
 * HTML buffer), WP Rocket's "Delay JS" cannot re-catch them — so once this loader
 * is live and excluded from delay, WP Rocket's Delay JS can be turned off.
 *
 * Kill-switch: ?mfs_delay=0 (per-request) or define('MFS_DELAY', false) (global)
 * → load both immediately, no gating (for debugging / PSI measurement).
 */

defined( 'ABSPATH' ) || exit;

if ( ! defined( 'MFS_GTM_ID' ) )            define( 'MFS_GTM_ID', 'GTM-T4JS5BJV' );
if ( ! defined( 'MFS_HS_PORTAL_ID' ) )      define( 'MFS_HS_PORTAL_ID', '148670517' );
if ( ! defined( 'MFS_DELAY_FALLBACK_MS' ) ) define( 'MFS_DELAY_FALLBACK_MS', 10000 );

add_action( 'wp_footer', 'mfs_print_delayed_thirdparty', 20 );

function mfs_print_delayed_thirdparty() {
	// No tracking in local Vite dev (mirrors the old footer.php / HubSpot guards).
	if ( defined( 'IS_VITE_DEVELOPMENT' ) && IS_VITE_DEVELOPMENT == true ) {
		return;
	}

	$immediate = ( isset( $_GET['mfs_delay'] ) && $_GET['mfs_delay'] === '0' )
	          || ( defined( 'MFS_DELAY' ) && MFS_DELAY === false );

	$gtm = wp_json_encode( MFS_GTM_ID );
	$hs  = wp_json_encode( MFS_HS_PORTAL_ID );
	$fb  = $immediate ? 0 : (int) MFS_DELAY_FALLBACK_MS;
	?>
<script id="mfs-delay">
(function(){
  var GTM=<?php echo $gtm; ?>,HS=<?php echo $hs; ?>,FB=<?php echo $fb; ?>,fired=false;
  var evts=['scroll','mousemove','touchstart','keydown','pointerdown','click'];
  function load(){
    if(fired){return;}
    fired=true;
    for(var i=0;i<evts.length;i++){window.removeEventListener(evts[i],load,{passive:true});}
    /* Stape Gateway custom loader (atlas.maverickframe.com) — generated by Stape, do not modify.
       It pushes gtm.start into dataLayer itself and injects gtm.js from the first-party domain. */
    !function(){"use strict";function l(e){for(var t=e,r=0,n=document.cookie.split(";");r<n.length;r++){var o=n[r].split("=");if(o[0].trim()===t)return o[1]}}function s(e){return localStorage.getItem(e)}function u(e){return window[e]}function A(e,t){e=document.querySelector(e);return t?null==e?void 0:e.getAttribute(t):null==e?void 0:e.textContent}var e=window,t=document,r="script",n="dataLayer",o="https://atlas.maverickframe.com",a="",i="bxqkwicnjcy",c="6vo1xrdv=",g="stapeUserId",v="",E="",d=!1;try{var d=!!g&&(m=navigator.userAgent,!!(m=new RegExp("Version/([0-9._]+)(.*Mobile)?.*Safari.*").exec(m)))&&16.4<=parseFloat(m[1]),f="stapeUserId"===g,I=d&&!f?function(e,t,r){void 0===t&&(t="");var n={cookie:l,localStorage:s,jsVariable:u,cssSelector:A},t=Array.isArray(t)?t:[t];if(e&&n[e])for(var o=n[e],a=0,i=t;a<i.length;a++){var c=i[a],c=r?o(c,r):o(c);if(c)return c}else console.warn("invalid uid source",e)}(g,v,E):void 0;d=d&&(!!I||f)}catch(e){console.error(e)}var m=e,g=(m[n]=m[n]||[],m[n].push({"gtm.start":(new Date).getTime(),event:"gtm.js"}),t.getElementsByTagName(r)[0]),v=I?"&bi="+encodeURIComponent(I):"",E=t.createElement(r),f=(d&&(i=8<i.length?i.replace(/([a-z]{8}$)/,"kp$1"):"kp"+i),!d&&a?a:o);E.async=!0,E.src=f+"/"+i+".js?"+c+v,null!=(e=g.parentNode)&&e.insertBefore(E,g)}();
    var h=document.createElement('script');
    h.id='hs-script-loader';h.async=true;h.defer=true;
    h.src='https://js-eu1.hs-scripts.com/'+HS+'.js';
    document.head.appendChild(h);
  }
  for(var i=0;i<evts.length;i++){window.addEventListener(evts[i],load,{passive:true});}
  setTimeout(load,FB);
})();
</script>
<?php
}
